import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ThemeConfigProvider from './components/ThemeConfigProvider.jsx';
import MuiThemeProvider from './components/MuiThemeProvider.jsx';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Ensure app renders dynamically to avoid prerender issues with client providers
export const dynamic = 'force-dynamic';
export const revalidate = 0;

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Wrap the entire app in ThemeConfigProvider so all pages can access website config
            fetched from the backend (name, logo, colors). */}
        <ThemeConfigProvider>
          <MuiThemeProvider>
            {children}
          </MuiThemeProvider>
        </ThemeConfigProvider>
      </body>
    </html>
  );
}
